### ISSUE TITLE
No support for old bitcoind versions?

### ISSUE THREAD

**Issue by gracenoah** [stevenroose/go-bitcoin-core-rpc#2]
Looks like some APIs (ImportAddressRescan in particular) are not backwards compatible with old versions of bitcoind. I can't find a good way to add compatibility without breaking changes. Any ideas?

**Comment by stevenroose** [comment]
You could always add a method with a `_v016` suffix or so..

**Comment by gracenoah** [comment]
I tired, but it would require a bigger refactor because you can't have two methods registered for the same RPC method :(

**Comment by stevenroose** [comment]
Is that really true (been a long time since code base)?? Because you have the "verbose" versions etc, no? Like different methods for different arguments provided...

Perhaps you mean one `Cmd` type per official method?

Perhaps having a branch per main version (like `v0.15`) would be an idea? But then the user needs to know upfront what version of Bitcoin Core he'd be dealing with.

**Comment by gracenoah** [comment]
Yeah, the issue is with the Cmd stuff.

Yep, I'm using a branch right now and I've updated the one API that I'm using that doesn't work. Another option is to always use the "old" version with the empty account. IIRC the new version of bitcoind is backwards compatible with the old API as long as the account string is empty.

**Comment by stevenroose** [comment]
Sorry, on phone so can't look into the source. But why exactly is it one
Cmd per command string? Is that map actually still used?
